module.exports = {
    NULL_VALUE: "필요한 값이 없습니다",
    OUT_OF_VALUE: "필요한 값이 잘못되었습니다",

    SIGN_UP_SUCCESS: "회원가입 성공",
    SIGN_UP_DUPLICATE: "이미 존재하는 회원입니다",
    SIGN_UP_ERROR: "유저 삽입 에러",
    SIGN_IN_SUCCESS: "로그인 성공",
    SIGN_IN_FAIL: "아이디/비밀번호가 틀렸습니다",
    SIGN_IN_ERROR: "유저 조회 에러",

    BANNER_INSERT_SUCCESS:  "배너 작성 성공",
    BANNER_UPDATE_SUCCESS:  "배너 수정 성공",
    BANNER_UPDATE_NOTHING:  "수정할 배너가 존재하지 않습니다",
    BANNER_SELECT_SUCCESS:  "배너 조회 성공",
    BANNER_DELETE_SUCCESS:  "배너 삭제 성공",
    BANNER_DELETE_NOTHING:  "삭제할 배너가 존재하지 않습니다",
    BANNER_INSERT_ERROR:    "배너 작성 에러",
    BANNER_UPDATE_ERROR:    "배너 수정 에러",
    BANNER_SELECT_ERROR:    "배너 조회 에러",
    BANNER_DELETE_ERROR:    "배너 삭제 에러",

    WEBTOON_INSERT_SUCCESS: "웹툰 작성 성공",
    WEBTOON_UPDATE_SUCCESS: "웹툰 수정 성공",
    WEBTOON_UPDATE_NOTHING: "수정할 웹툰이 존재하지 않습니다",
    WEBTOON_SELECT_SUCCESS: "웹툰 조회 성공",
    WEBTOON_SELECT_NOTHING: "해당 웹툰이 존재하지 않습니다",
    WEBTOON_DELETE_SUCCESS: "웹툰 삭제 성공",
    WEBTOON_DELETE_NOTHING: "삭제할 웹툰이 존재하지 않습니다",
    WEBTOON_INSERT_ERROR:   "웹툰 작성 에러",
    WEBTOON_UPDATE_ERROR:   "웹툰 수정 에러",
    WEBTOON_SELECT_ERROR:   "웹툰 조회 에러",
    WEBTOON_DELETE_ERROR:   "웹툰 삭제 에러",

    WEBTOON_LIKE_INSERT_SUCCESS: "웹툰 좋아요 성공",
    WEBTOON_LIKE_SELECT_SUCCESS: "웹툰 좋아요 여부 조회 성공",
    WEBTOON_LIKE_DELETE_SUCCESS: "웹툰 좋아요 취소 성공",
    WEBTOON_LIKE_DELETE_NOTHING: "웹툰을 좋아요 하지 않았습니다",
    WEBTOON_LIKE_INSERT_ERROR:   "웹툰 좋아요 에러",
    WEBTOON_LIKE_SELECT_ERROR:   "웹툰 좋아요 여부 조회 에러",
    WEBTOON_LIKE_DELETE_ERROR:   "웹툰 좋아요 취소 에러",

    EPISODE_INSERT_SUCCESS: "에피소드 작성 성공",
    EPISODE_UPDATE_SUCCESS: "에피소드 수정 성공",
    EPISODE_UPDATE_NOTHING: "수정할 에피소드가 존재하지 않습니다",
    EPISODE_SELECT_SUCCESS: "에피소드 조회 성공",
    EPISODE_SELECT_NOTHING: "해당 에피소드가 존재하지 않습니다",
    EPISODE_DETAIL_SELECT_SUCCESS: "에피소드 상세 조회 성공",
    EPISODE_DELETE_SUCCESS: "에피소드 삭제 성공",
    EPISODE_DELETE_NOTHING: "삭제할 에피소드가 존재하지 않습니다",
    EPISODE_INSERT_ERROR:   "에피소드 작성 에러",
    EPISODE_UPDATE_ERROR:   "에피소드 수정 에러",
    EPISODE_SELECT_ERROR:   "에피소드 조회 에러",
    EPISODE_DETAIL_SELECT_ERROR:   "에피소드 상세 조회 에러",
    EPISODE_DELETE_ERROR:   "에피소드 삭제 에러",

    COMMENT_INSERT_SUCCESS: "댓글 작성 성공",
    COMMENT_UPDATE_SUCCESS: "댓글 수정 성공",
    COMMENT_UPDATE_NOTHING: "수정할 댓글이 존재하지 않습니다",
    COMMENT_SELECT_SUCCESS: "댓글 조회 성공",
    COMMENT_DELETE_SUCCESS: "댓글 삭제 성공",
    COMMENT_DELETE_NOTHING: "삭제할 댓글이 존재하지 않습니다",
    COMMENT_INSERT_ERROR:   "댓글 작성 에러",
    COMMENT_UPDATE_ERROR:   "댓글 수정 에러",
    COMMENT_SELECT_ERROR:   "댓글 조회 에러",
    COMMENT_DELETE_ERROR:   "댓글 삭제 에러",

    INVALID_TOKEN: "잘못된 형식의 토큰입니다.",
    EMPTY_TOKEN: "토큰값이 존재하지 않습니다.",
    EXPRIED_TOKEN: "만료된 토큰입니다.",
    EMPTY_REFRESH_TOKEN: "재발급 토큰이 존재하지 않습니다.",
    CREATE_TOKEN: "토큰 발급 완료.",
    REFRESH_TOKEN: "토큰 재발급 완료.",

    NO_SELECT_AUTHORITY: "조회 권한 없음.",
    USER_SELECTED: "회원 조회 성공."
};